function heatflux = import_heatflux(filename)
%IMPORTFILE Import data from a text file XY and elevations
%  TOPOGRAPHY1 = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  TOPOGRAPHY1 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  topography1 = import_heatflux("/Users/ponsm/Desktop/modelblogin/model/globalscale/anulus2d/mobility_function/test_topo/topography.00000", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 22-Feb-2023 10:43:46

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["VarName1", "x", "y"];
opts.VariableTypes = ["double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Import the data
heatflux = readtable(filename, opts);

end