function lithosphere = import_lithosphere_sphere(filename, dataLines)
%IMPORTFILE Import data from a text file
%  LITHOSPHERE = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  LITHOSPHERE = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  lithosphere = importfile("/Users/ponsm/Desktop/Model_sphere/Models_HLRN/P01a_Pangea_1GPa_Mantle_C40MPa_LR/lithosphere_0099.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 15-Jan-2024 16:27:24

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 59);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Time", "Divergence", "Gradient0", "Gradient1", "Gradient2", "Gradient3", "Gradient4", "Gradient5", "Gradient6", "Gradient7", "Gradient8", "Normals0", "Normals1", "Normals2", "Points0", "Points1", "Points2", "QCriterion", "T", "Vorticity0", "Vorticity1", "Vorticity2", "continent", "current_cohesions", "current_friction_angles", "current_yield_stresses", "density", "depth", "nonadiabatic_temperature", "oceanic_age", "p", "plastic_yielding", "principal_stress_direction_10", "principal_stress_direction_11", "principal_stress_direction_12", "principal_stress_direction_20", "principal_stress_direction_21", "principal_stress_direction_22", "principal_stress_direction_30", "principal_stress_direction_31", "principal_stress_direction_32", "shear_stress0", "shear_stress1", "shear_stress2", "shear_stress3", "shear_stress4", "shear_stress5", "shear_stress6", "shear_stress7", "shear_stress8", "specific_heat", "strain_rate", "v_phi", "v_r", "v_theta", "velocity0", "velocity1", "velocity2", "viscosity"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
lithosphere = readtable(filename, opts);

end