function data = import_layers_sphere(filename, dataLines)
%IMPORTFILE Import data from a text file
%  DEPTHS = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  DEPTHS = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  depths = importfile("/Users/ponsm/Desktop/Model_sphere/Models_HLRN/P01a_Pangea_1GPa_Mantle_C40MPa_LR/depths_0099.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 15-Jan-2024 16:28:54
% filename=fullfile(path_model, 'depths_0106.csv');

%% Extract variable name from the file path
[~, name, ~] = fileparts(filename);
validVariableName = genvarname(name);

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

% Open the file for reading
fileID = fopen(filename, 'r');

% Check if the file was opened successfully
if fileID == -1
    error('Unable to open file: %s', filename);
end

% Read the header line
headerLine = fgetl(fileID);
headers = textscan(headerLine, '%s', 'Delimiter', ',');

% Remove double quotes from variable names
headers{1} = strrep(headers{1}, '"', '');

% Read the data using textscan
formatSpec = repmat('%f', 1, numel(headers{1}));
data = textscan(fileID, formatSpec, 'Delimiter', ',');

% Close the file
fclose(fileID);

% Convert the data to a table using the modified headers
data = array2table(cell2mat(data), 'VariableNames', headers{1});

end