function geofeatures = import_geofeature_statistics(filename, dataLines)
%IMPORTFILE Import data from a text file
%  DISTRIBUTIONP01APANGEA1GPAMANTLEC40MPALR = IMPORTFILE(FILENAME) reads
%  data from text file FILENAME for the default selection.  Returns the
%  data as a table.
%
%  DISTRIBUTIONP01APANGEA1GPAMANTLEC40MPALR = IMPORTFILE(FILE,
%  DATALINES) reads data for the specified row interval(s) of text file
%  FILENAME. Specify DATALINES as a positive scalar integer or a N-by-2
%  array of positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  DistributionP01aPangea1GPaMantleC40MPaLR = importfile("/Users/ponsm/Nextcloud/Postdoc_MEET/Modelling/Postprocess_ASPECT/Distribution_P01a_Pangea_1GPa_Mantle_C40MPa_LR.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 28-Jan-2024 18:13:06

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 9);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Time", "NumPlumes", "NumSubductions", "NumSubduction_connected", "Depths", "Maxferet_mean", "Maxferet_max", "Maxferet_in", "nferet"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
geofeatures = readtable(filename, opts);

end